### ISSUE TITLE
src/rod_align_cuda.cpp:1:21: fatal error: THC/THC.h: No such file or directory

### ISSUE THREAD

**Issue by Du-Yao** [intchous/SmartText#3]
我使用的pytorch版本是1.13，cuda11.6，在编译rod_align 和roi_align时报错，如题目，请问该如何解决。

**Comment by intchous** [comment]
> 
也许是因为新版的 pytorch 移除了 THC files, 尝试把 pytorch 版本降到 1.10 以下看看

**Comment by CLeaf1023** [comment]
pytorch1.6也不行啊

**Comment by CLeaf1023** [comment]
fatal error: THC/THC.h: No such file or directory 
降低版本没有效果，有什么其他的方法吗

**Comment by undcloud** [comment]
我用docker环境可以跑通，好像仍旧有这个编译问题，但是程序能运行，就很奇怪，经验分享给大家，，，

docker pull nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by A-urora** [comment]
replace  #include <THC/THC.h> in xxx_align_cuda.cpp
```cpp
// #include <THC/THC.h>
#include <ATen/cuda/CUDAContext.h>
#include <ATen/cuda/CUDAEvent.h>
```

remove #include <THC/THC.h> in xxx_align_kernel.h

add #include <cstdio> in xxx_align_kernel.cu

I work in torch==1.13.1+cu116, torchaudio==0.13.1+cu116, torchvision==0.14.1+cu116

<img width="243" alt="Image" src="https://github.com/user-attachments/assets/97790e19-61cf-487e-89fc-2e6d42697a4d" />
